### PR TITLE
correct spelling mistake

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Change LGTM, but could you [sign-off your commit]( https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work)?

also ping @dmcgowan

**Comment by dmcgowan** [comment]
thanks @thaJeztah, I will merge this once the commit is signed

**Comment by EdwardBetts** [comment]
Done.

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
